const phrases = [
    "a bad apple",
    "a bunch of",
    "a doozy",
    "a for effort",
    "a hangup",
    "a hot potato",
    "a kickback",
    "a ripoff",
    "a screwup",
    "a tossup",
    "acid test",
    "adult peter",
    "all heart",
    "all set",
    "all thumbs",
    "all wet",
    "an old soul",
    "an open book",
    "at best",
    "at least",
    "awake diver",
    "baby boomer",
    "bad blood",
    "bad hair day",
    "be my guest",
    "bed head",
    "bed of roses",
    "big cheese",
    "big shot",
    "big wheel",
    "black sheep",
    "blew me away",
    "blow a fuse",
    "blue blood",
    "blue law",
    "boxed in",
    "break a leg",
    "break even",
    "brought up",
    "buffy reins",
    "burned out",
    "busy bee",
    "buy a lemon",
    "by the book",
    "call it a day",
    "cat nap",
    "cheer up",
    "chow down",
    "civic feces",
    "clean slate",
    "clear as mud",
    "close shave",
    "cold feet",
    "come alive",
    "come clean",
    "cook up",
    "crack a book",
    "crunch time",
    "cup of joe",
    "curve ball",
    "cute as a bug",
    "dark horse",
    "dawned on me",
    "dead quiet",
    "dead ringer",
    "dead tired",
    "deadend job",
    "deep down",
    "dirt cheap",
    "do or die",
    "do you have",
    "dozen plaza",
    "draw a blank",
    "drop by",
    "dry run",
    "easy does it",
    "eat crow",
    "eat my hat",
    "eaten syrah",
    "eaten tempo",
    "elven broth",
    "fancy pants",
    "fat cat",
    "field day",
    "filthy rich",
    "flea market",
    "fly the coop",
    "fool around",
    "fool's gold",
    "forty winks",
    "freak out",
    "fresh mayer",
    "fresh vogue",
    "from day one",
    "full of crap",
    "gain ground",
    "get a move on",
    "get over it",
    "get the sack",
    "get with it",
    "getting by",
    "go bananas",
    "go belly up",
    "go bonkers",
    "go fly a kite",
    "go fry an egg",
    "go haywire",
    "go it alone",
    "go postal",
    "go south",
    "go to town",
    "golden age",
    "good egg",
    "good for you",
    "good luck",
    "good to know",
    "goof off",
    "gravy train",
    "gray area",
    "green room",
    "green thumb",
    "guinea pig",
    "gung ho",
    "gut feeling",
    "hang tight",
    "hard sell",
    "he yelled",
    "he's a creep",
    "he's broke",
    "head honcho",
    "hissy ankle",
    "hissy fit",
    "hit me up",
    "hit pay dirt",
    "hit the hay",
    "hit the road",
    "hit the sack",
    "hopping mad",
    "how are you",
    "how ya doin'",
    "humid china",
    "i overslept",
    "i'm going to",
    "i'm single",
    "in a bind",
    "in a jam",
    "in a pinch",
    "in a rut",
    "in charge of",
    "in high gear",
    "in hot water",
    "in my book",
    "in spades",
    "in stitches",
    "in the bag",
    "in the black",
    "in the least",
    "in the loop",
    "in the pink",
    "in the red",
    "in the way",
    "it happens",
    "it's a cinch",
    "it's on me",
    "itchy feet",
    "ivory tower",
    "joshing me",
    "jump the gun",
    "junk food",
    "just now",
    "keep my cool",
    "keep up with",
    "keyed drank",
    "keyed up",
    "knock it off",
    "know zip",
    "laid off",
    "last straw",
    "lay an egg",
    "leery taker",
    "live it up",
    "long face",
    "lose touch",
    "lost at sea",
    "lost my head",
    "luck out",
    "lucky break",
    "lucky dog",
    "make a scene",
    "make tracks",
    "make waves",
    "mark time",
    "midas touch",
    "money talks",
    "mumbo jumbo",
    "muted bases",
    "my bad",
    "nest egg",
    "night owl",
    "no big deal",
    "no comment",
    "no dice",
    "no problem",
    "not bad",
    "odd man out",
    "off the cuff",
    "off the hook",
    "off the wall",
    "oh no",
    "old school",
    "on a tear",
    "on the ball",
    "on the blink",
    "on the cheap",
    "on the dot",
    "on the fence",
    "on the fly",
    "on the fritz",
    "on the house",
    "on the level",
    "on the line",
    "on the spot",
    "on thin ice",
    "out of date",
    "out of order",
    "out to lunch",
    "peg out",
    "penal rocks",
    "perky plaza",
    "peter out",
    "pig out",
    "pipe down",
    "pipe dream",
    "piped villa",
    "pitch dark",
    "pitch in",
    "play by ear",
    "poker face",
    "pretty good",
    "pull it off",
    "pull rank",
    "puppy love",
    "quick heads",
    "quick words",
    "raise cain",
    "razed cabot",
    "real mccoy",
    "red flag",
    "red herring",
    "ring a bell",
    "run amok",
    "run errands",
    "run the show",
    "sales pitch",
    "saved snead",
    "say uncle",
    "screw up",
    "sea legs",
    "shake a leg",
    "shiny eater",
    "shoot hoops",
    "short eater",
    "sick as a dog",
    "sit tight",
    "sixth sense",
    "slim chance",
    "small world",
    "smell a rat",
    "snuff basin",
    "sold me out",
    "sour grapes",
    "spiky drank",
    "spiky dumps",
    "spin doctor",
    "square meal",
    "sweat blood",
    "take it easy",
    "talk turkey",
    "tall order",
    "tall story",
    "thanks a lot",
    "that's ok",
    "the big easy",
    "the pits",
    "to be loaded",
    "to black out",
    "to bomb",
    "to butt in",
    "to cry wolf",
    "to drop by",
    "to get rid of",
    "to give in",
    "to go dutch",
    "to pony up",
    "to the hilt",
    "top dog",
    "touch and go",
    "touch base",
    "train wreck",
    "trial stole",
    "trial words",
    "true blue",
    "tudor piles",
    "up a gum tree",
    "up for grabs",
    "up in arms",
    "up in the air",
    "up to snuff",
    "veg out",
    "wet blanket",
    "what a pity",
    "what a shame",
    "white lie",
    "widen broth",
    "winging it",
    "yeah right",
    "you bet",
    "zip it"
];

if (typeof module !== 'undefined') {
    module.exports = { phrases };
}