const phrases = [
    "a bad apple",
    "a baker is dozen",
    "a ballpark figure",
    "a bit",
    "a blessing in disguise",
    "a bone to pick",
    "a breath of fresh air",
    "a bunch of",
    "a chip on your shoulder",
    "a dime a dozen",
    "a doozy",
    "a doubting thomas",
    "a far cry from",
    "a fifth wheel",
    "a flash in the pan",
    "a for effort",
    "a fork in the road",
    "a good samaritan",
    "a hard nut to crack",
    "a hot potato",
    "a kickback",
    "a little bird told me",
    "a little bit",
    "a memory like a sieve",
    "a penny for your thoughts",
    "a perfect storm",
    "a piece of cake",
    "a pinch of salt",
    "a ray of sunshine",
    "a rose",
    "a screw loose",
    "a screwup",
    "a smart cookie",
    "a snowball effect",
    "a stone is throw",
    "a storm in a teacup",
    "a storm is brewing",
    "a surefire way",
    "a sweet tooth",
    "ace in the hole",
    "ace up the sleeve",
    "acid test",
    "across the board",
    "add fuel to the fire",
    "add insult to injury",
    "against the clock",
    "ahead of schedule",
    "all bark and no bite",
    "all bets are off",
    "all greek to me",
    "all heart",
    "all in the same boat",
    "all kidding aside",
    "all over the map",
    "all set",
    "all thumbs",
    "all wet",
    "along for the ride",
    "an old soul",
    "an open book",
    "are you doing anything",
    "are you free",
    "armchair quarterback",
    "armed to the teeth",
    "as busy as a bee",
    "as easy as abc",
    "as easy as pie",
    "as happy as a clam",
    "as quiet as a mouse",
    "as right as rain",
    "as the crow flies",
    "as white as a ghost",
    "as white as a sheet",
    "at best",
    "at least",
    "at loggerheads",
    "at the crack of dawn",
    "baby boomer",
    "back to basics",
    "back to square one",
    "back to the drawing board",
    "backhanded compliment",
    "backseat driver",
    "bad blood",
    "bad hair day",
    "barking up the wrong tree",
    "batting a thousand",
    "be my guest",
    "bear in mind",
    "beat a hasty retreat",
    "beat around the bush",
    "beat someone to the draw",
    "beat someone to the punch",
    "beat the bushes",
    "beating a dead horse",
    "beating around the bush",
    "bed head",
    "bed of roses",
    "before you know it",
    "behind someone is back",
    "behind the eight ball",
    "belt and suspenders",
    "bend over backward",
    "bent out of shape",
    "beside oneself",
    "beside the point",
    "bet the ranch",
    "better late than never",
    "beyond the pale",
    "big cheese",
    "big shot",
    "big wheel",
    "bigger bang for your buck",
    "bite the bullet",
    "bite the dust",
    "bite your tongue",
    "bitter pill to swallow",
    "black and blue",
    "black market",
    "black sheep",
    "black tie event",
    "blackball someone",
    "blast from the past",
    "blaze a trail",
    "blew me away",
    "blonde bombshell",
    "blow a fuse",
    "blow hot and cold",
    "blow off steam",
    "blow one is top",
    "blowing smoke",
    "blue blood",
    "blue law",
    "boiling point",
    "bolt from the blue",
    "bone of contention",
    "bottom of the barrel",
    "boxed in",
    "bread and butter",
    "break a leg",
    "break even",
    "break someone is heart",
    "break the bank",
    "break the ice",
    "break the news",
    "breeze through",
    "bright and early",
    "bring down the house",
    "bring home the bacon",
    "bring my a game",
    "brought up",
    "brownie points",
    "brushed me off",
    "bull in a china shop",
    "burgers and dogs",
    "burn bridges",
    "burn the midnight oil",
    "burned out",
    "bury the hatchet",
    "busy bee",
    "butter someone up",
    "button one is lip",
    "buy a lemon",
    "buy something for a song",
    "by hook or by crook",
    "by the book",
    "by word of mouth",
    "call a spade a spade",
    "call it a day",
    "call the shots",
    "call their bluff",
    "calm before the storm",
    "calm someone down",
    "can not keep up",
    "card sharp or card shark",
    "carry the ball",
    "cast pearls before swine",
    "castle in the sky",
    "cat nap",
    "catch some rays",
    "catch some zs",
    "catch someone is eye",
    "catch the bus",
    "catching up",
    "change of heart",
    "charley horse",
    "charmed life",
    "chasing rainbows",
    "checkered past",
    "cheer up",
    "chew someone out",
    "chew something over",
    "chewing the fat",
    "chow down",
    "chuffed to bits",
    "clean slate",
    "clean someone out",
    "clear as mud",
    "clear the air",
    "climb the walls",
    "close but no cigar",
    "close shave",
    "clown around",
    "coin a new term",
    "coin a phrase",
    "cold feet",
    "cold shoulder",
    "collecting dust",
    "come a long way",
    "come alive",
    "come clean",
    "come down with a cold",
    "come hell or high water",
    "come in handy",
    "come out of your shell",
    "come rain or shine",
    "comfort food",
    "computer crashed",
    "cook someone is goose",
    "cook up",
    "cooked the books",
    "cool as a cucumber",
    "cool your jets",
    "cost me a mint",
    "couch potato",
    "could not care less",
    "country mile",
    "cover a lot of ground",
    "crack a book",
    "crack open a cold one",
    "crack someone up",
    "crank out a paper",
    "cream of the crop",
    "crocodile tears",
    "cross your fingers",
    "crunch time",
    "cup of joe",
    "curiosity killed the cat",
    "curve ball",
    "cut and dried",
    "cut class",
    "cut the mustard",
    "cut them some slack",
    "cut to the chase",
    "cut to the quick",
    "cute as a bug",
    "cutting corners",
    "dark horse",
    "dawned on me",
    "dead from the neck up",
    "dead in the water",
    "dead quiet",
    "dead ringer",
    "dead tired",
    "dead to the world",
    "deep down",
    "diamond in the rough",
    "dig in your heels",
    "dirt cheap",
    "dish the dirt",
    "divide the spoils",
    "do not hold your breath",
    "do or die",
    "do someone a good turn",
    "does not hold water",
    "dog and pony show",
    "dog days of summer",
    "dollars for doughnuts",
    "done to a turn",
    "doom and gloom",
    "double whammy",
    "down in the dumps",
    "down in the mouth",
    "down the tube",
    "down to the wire",
    "dragging your feet",
    "draw a blank",
    "drawing card",
    "dressed to kill",
    "drive someone up the wall",
    "driving me nuts",
    "drop by",
    "drop in the bucket",
    "drop someone a line",
    "dry run",
    "ducks in a row",
    "eager beaver",
    "easy does it",
    "eat crow",
    "eat like a bird",
    "eat like a horse",
    "eat my hat",
    "eat your heart out",
    "egg on your face",
    "elevator pitch",
    "every dog has his day",
    "every now and then",
    "exact change",
    "excuse my french",
    "face the music",
    "fair and square",
    "fair to middling",
    "fall by the wayside",
    "fall off the wagon",
    "fall on deaf ears",
    "fall to pieces",
    "fancy pants",
    "fashion victim",
    "fat cat",
    "feather in one is cap",
    "feather one is nest",
    "feeding frenzy",
    "feel the pinch",
    "feeling blue",
    "fender bender",
    "field day",
    "fifteen minutes of fame",
    "fight an uphill battle",
    "fight tooth and nail",
    "fill in the blanks",
    "filthy rich",
    "find your feet",
    "fish out of water",
    "fit as a fiddle",
    "fit to be tied",
    "fits and starts",
    "fix someone is wagon",
    "fixed in your ways",
    "flavor of the month",
    "flea market",
    "flesh and blood",
    "fly in the ointment",
    "fly off the handle",
    "fly the coop",
    "foam at the mouth",
    "follow the money",
    "food for thought",
    "fool around",
    "fool is gold",
    "foot in the door",
    "for crying out loud",
    "for heaven is sake",
    "for the birds",
    "fork over",
    "fortune favors the bold",
    "forty winks",
    "freak out",
    "from day one",
    "from rags to riches",
    "from the word go",
    "from time to time",
    "full of crap",
    "full of hot air",
    "full steam ahead",
    "gain ground",
    "get a handle on something",
    "get a hold of something",
    "get a hold of yourself",
    "get a move on",
    "get a second wind",
    "get a word in edgewise",
    "get along with each other",
    "get back to someone",
    "get down to brass tacks",
    "get down to business",
    "get from a to b",
    "get hold of someone",
    "get in someone is hair",
    "get into deep water",
    "get it off my chest",
    "get it through your head",
    "get off your high horse",
    "get one is feet wet",
    "get out of hand",
    "get over it",
    "get something for peanuts",
    "get the green light",
    "get the hang of it",
    "get the message",
    "get the sack",
    "get to the point",
    "get wind of something",
    "get with it",
    "get your act together",
    "get your dander up",
    "get your goat",
    "get your head around it",
    "getting by",
    "getting on my last nerve",
    "getting on my nerves",
    "give props to",
    "give someone a hard time",
    "give someone short shrift",
    "give them the slip",
    "go against the grain",
    "go around in circles",
    "go bananas",
    "go belly up",
    "go bonkers",
    "go cold turkey",
    "go down in flames",
    "go fly a kite",
    "go fry an egg",
    "go haywire",
    "go it alone",
    "go off the deep end",
    "go out on a limb",
    "go overboard",
    "go postal",
    "go south",
    "go the extra mile",
    "go the whole hog",
    "go to pieces",
    "go to the dogs",
    "go to town",
    "go up in smoke",
    "go with the flow",
    "goes without saying",
    "golden age",
    "golden opportunity",
    "good egg",
    "good riddance",
    "good to know",
    "goof off",
    "got the cream",
    "got the third degree",
    "got their hackles up",
    "grasping at straws",
    "graveyard shift",
    "gravy train",
    "gray area",
    "grease monkey",
    "greased lightning",
    "great minds think alike",
    "green around the gills",
    "green room",
    "green thumb",
    "grin and bear it",
    "guinea pig",
    "gung ho",
    "gut feeling",
    "hair is breadth",
    "hair of the dog",
    "half the battle",
    "hammering out a deal",
    "hand in glove",
    "hand over fist",
    "hang in there",
    "hang on a sec",
    "hang tight",
    "hard sell",
    "haste makes waste",
    "have an axe to grind",
    "have hell to pay",
    "have something down pat",
    "have time off",
    "have two left feet",
    "he is off his rocker",
    "head and shoulders above",
    "head honcho",
    "head in the clouds",
    "head over heels",
    "hear it on the grapevine",
    "her own weight",
    "here and there",
    "high on the hog",
    "hissy fit",
    "hit it on the nose",
    "hit me up",
    "hit pay dirt",
    "hit the books",
    "hit the ceiling",
    "hit the hay",
    "hit the jackpot",
    "hit the road",
    "hit the sack",
    "hold the fort",
    "hold your horses",
    "hold your tongue",
    "holding the bag",
    "hopping mad",
    "horse around",
    "hot under the collar",
    "i am losing it",
    "i can not imagine",
    "i have a boyfriend",
    "i have no idea",
    "i love",
    "i really should",
    "i suck at something",
    "i was not born yesterday",
    "icing on the cake",
    "if i remember correctly",
    "if worst comes to worst",
    "ignorance is bliss",
    "in a bind",
    "in a jam",
    "in a nutshell",
    "in a pinch",
    "in a rut",
    "in charge of",
    "in full swing",
    "in high gear",
    "in hot water",
    "in my book",
    "in my element",
    "in seventh heaven",
    "in spades",
    "in stitches",
    "in the bag",
    "in the black",
    "in the boondocks",
    "in the chips",
    "in the doghouse",
    "in the least",
    "in the long run",
    "in the loop",
    "in the nick of time",
    "in the pink",
    "in the red",
    "in the sticks",
    "in the way",
    "it is a scorcher",
    "it is crunch time",
    "it is in the bag",
    "it is not rocket science",
    "it takes two to tango",
    "itchy feet",
    "ivory tower",
    "joined at the hip",
    "joshing me",
    "jump on the bandwagon",
    "jump the gun",
    "jump through hoops",
    "junk food",
    "jury is still out",
    "just a moment",
    "just around the corner",
    "just now",
    "keep in mind",
    "keep it under control",
    "keep it under wraps",
    "keep me in the loop",
    "keep me posted",
    "keep my cool",
    "keep my head above water",
    "keep something at bay",
    "keep the ball rolling",
    "keep up with",
    "keep you posted",
    "keep your chin up",
    "keep your head",
    "keep your mouth shut",
    "keep your nose clean",
    "keep your wits about you",
    "kept in the dark",
    "keyed up",
    "kick up your heels",
    "kill the mood",
    "kit and caboodle",
    "knock into a cocked hat",
    "knock it off",
    "knock on wood",
    "know the ins and outs",
    "know the ropes",
    "know your onions",
    "know zip",
    "knuckle under",
    "labor of love",
    "laid off",
    "lap of luxury",
    "last but not least",
    "last straw",
    "lay an egg",
    "lay down the law",
    "learn by rote",
    "learn the ropes",
    "learned my lesson",
    "leave me alone",
    "leave no stone unturned",
    "leave well enough alone",
    "left me in the lurch",
    "left out in the cold",
    "left someone behind",
    "lend me your ear",
    "lend someone a hand",
    "let bygones be bygones",
    "let sleeping dogs lie",
    "let someone off the hook",
    "let the dust settle",
    "let your hair down",
    "letter perfect",
    "level playing field",
    "life of riley",
    "light of my life",
    "like a deer in headlights",
    "like clockwork",
    "like pulling teeth",
    "like riding a bicycle",
    "like there is no tomorrow",
    "live and learn",
    "live and let live",
    "live it up",
    "living the dream",
    "long face",
    "long in the tooth",
    "look at the big picture",
    "look before you leap",
    "look like a million bucks",
    "loose cannon",
    "lose one is shirt",
    "lose touch",
    "lose your marbles",
    "lose your touch",
    "lost at sea",
    "lost my head",
    "luck out",
    "lucky break",
    "lucky dog",
    "mad as a hornet",
    "made for each other",
    "make a beeline for",
    "make a big stink",
    "make a long story short",
    "make a pit stop",
    "make a scene",
    "make ends meet",
    "make eyes at someone",
    "make no bones about",
    "make out like a bandit",
    "make the grade",
    "make tracks",
    "make waves",
    "make yourself at home",
    "man is best friend",
    "mark time",
    "meat and potatoes",
    "meet halfway",
    "mickey mouse job",
    "midas touch",
    "middle of the road",
    "mind your own beeswax",
    "miss the boat",
    "money talks",
    "money to burn",
    "more bang for your buck",
    "more than i bargained for",
    "more than meets the eye",
    "move some things around",
    "mum is the word",
    "mumbo jumbo",
    "my bad",
    "my flight was delayed",
    "my hands are tied",
    "my heart is set on",
    "my neck of the woods",
    "nest egg",
    "new kid on the block",
    "new york minute",
    "night owl",
    "nip something in the bud",
    "no big deal",
    "no dice",
    "no rhyme or reason",
    "not a spark of decency",
    "not worth a red cent",
    "number cruncher",
    "odd man out",
    "off on the wrong foot",
    "off the cuff",
    "off the hook",
    "off the record",
    "off the wall",
    "oh no",
    "old school",
    "on a shoestring",
    "on a tear",
    "on a treadmill",
    "on cloud nine",
    "on pins and needles",
    "on the ball",
    "on the blink",
    "on the cheap",
    "on the dot",
    "on the fence",
    "on the fly",
    "on the fritz",
    "on the house",
    "on the level",
    "on the line",
    "on the same page",
    "on the spot",
    "on the up and up",
    "on the warpath",
    "on thin ice",
    "once and for all",
    "once in a blue moon",
    "one fell swoop",
    "open a can of worms",
    "out of date",
    "out of left field",
    "out of my hands",
    "out of order",
    "out of the blue",
    "out of the question",
    "out of the woods",
    "out of this world",
    "out on the town",
    "out to lunch",
    "over my dead body",
    "packed like sardines",
    "pain in the neck",
    "paint the town red",
    "paint you a picture",
    "pandora is box",
    "paper pusher",
    "par for the course",
    "pardon my french",
    "party animal",
    "pass the buck",
    "passed the course",
    "pay a pretty penny",
    "pay the piper",
    "pay through the nose",
    "pedal to the metal",
    "peg out",
    "peter out",
    "pick up the tab",
    "pick up your ears",
    "pie in the sky",
    "pig out",
    "pipe down",
    "pipe dream",
    "pitch dark",
    "pitch in",
    "play by ear",
    "play devil is advocate",
    "play hardball",
    "play second fiddle",
    "playing dumb",
    "playing with fire",
    "poker face",
    "pound the pavement",
    "power dressing",
    "pride comes before a fall",
    "pull his",
    "pull it off",
    "pull out all the stops",
    "pull rank",
    "pull someone is leg",
    "pull strings",
    "pull the plug",
    "pull up stakes",
    "pull your chain",
    "pull yourself together",
    "pulling my leg",
    "puppy love",
    "pushing your luck",
    "put a sock in it",
    "put in their place",
    "put my foot down",
    "put on my thinking cap",
    "put our heads together",
    "put someone on the spot",
    "put something on ice",
    "put the squeeze",
    "put your finger on it",
    "quality time",
    "racking my brain",
    "rain on someone is parade",
    "rain or shine",
    "raise cain",
    "read someone the riot act",
    "real mccoy",
    "red flag",
    "red herring",
    "red in the face",
    "red letter day",
    "rest on one is laurels",
    "right this way",
    "ring a bell",
    "roll out the red carpet",
    "rolling in it",
    "rub elbows with someone",
    "ruffle feathers",
    "rule of thumb",
    "run amok",
    "run errands",
    "run its course",
    "run like the wind",
    "run one is mouth off",
    "run out of steam",
    "run the show",
    "running on fumes",
    "sail close to the wind",
    "sales pitch",
    "salt of the earth",
    "saved by the bell",
    "saved someone is skin",
    "saving for a rainy day",
    "say uncle",
    "say your piece",
    "school of thought",
    "screw up",
    "screws on someone",
    "sea legs",
    "security blanket",
    "see eye to eye",
    "see the big picture",
    "see the light",
    "see through someone",
    "sell like hotcakes",
    "sell someone short",
    "set my teeth on edge",
    "shake a leg",
    "shape up or ship out",
    "sharp as a tack",
    "shell out money",
    "shoestring budget",
    "shoot from the hip",
    "shoot hoops",
    "shoot off one is mouth",
    "shoot the breeze",
    "shot in the arm",
    "shot in the dark",
    "show of hands",
    "sick as a dog",
    "sit tight",
    "sitting pretty",
    "sixth sense",
    "skeleton in the closet",
    "skelton crew",
    "skip class",
    "slap on the wrist",
    "sleep like a log",
    "slim chance",
    "slip of the tongue",
    "small world",
    "smell a rat",
    "smoke and mirrors",
    "smoke like a chimney",
    "snowed under",
    "so far so good",
    "sold me out",
    "something is killing me",
    "something sucks",
    "something to crow about",
    "sour grapes",
    "speak of the devil",
    "spice things up",
    "spill the beans",
    "spin doctor",
    "spitting image",
    "splitting hairs",
    "spread too thin",
    "square meal",
    "squeaky clean",
    "stab someone in the back",
    "stand my ground",
    "stay in touch",
    "stay on budget",
    "steal someone is thunder",
    "step up your game",
    "stew in your own juices",
    "stick to your guns",
    "sticking points",
    "sticky fingers",
    "stop on a dime",
    "stretch the truth",
    "strike it rich",
    "string someone along",
    "stuffed shirt",
    "swallow your pride",
    "sweat blood",
    "sweating bullets",
    "take a rain check",
    "take a shine to something",
    "take it easy",
    "take something by storm",
    "take something in stride",
    "take the cake",
    "take the floor",
    "take the plunge",
    "taken for a ride",
    "talk a blue streak",
    "talk of the town",
    "talk someone is ear off",
    "talk through one is hat",
    "talk to the hand",
    "talk turkey",
    "talking shop",
    "tall order",
    "tall story",
    "tell me about it",
    "test the waters",
    "that hit the spot",
    "that is all she wrote",
    "that is the last straw",
    "that is to say",
    "that is wicked",
    "that ship has sailed",
    "the apple of my eye",
    "the bee is knees",
    "the best of both worlds",
    "the big apple",
    "the big easy",
    "the bottom line",
    "the boys in blue",
    "the burning question",
    "the cat is meow",
    "the elephant in the room",
    "the eleventh hour",
    "the gift of the gab",
    "the last minute",
    "the lion is share",
    "the munchies",
    "the other day",
    "the patience of job",
    "the pits",
    "the road less travelled",
    "the same wavelength",
    "the school of hard knocks",
    "the straight and narrow",
    "the tide has turned",
    "the tip of the iceberg",
    "the whole nine yards",
    "they were thrown together",
    "think outside the box",
    "third time is a charm",
    "this is the life",
    "three sheets to the wind",
    "threw me for a loop",
    "through thick and thin",
    "throw a curve",
    "throw a curveball",
    "throw caution to the wind",
    "thrown to the wolves",
    "tickled pink",
    "tighten your belt",
    "tilt at windmills",
    "time is money",
    "to be a chicken",
    "to be beside yourself",
    "to be closefisted",
    "to be loaded",
    "to be named after",
    "to be up to something",
    "to beat the band",
    "to bend someone is ear",
    "to black out",
    "to blow your own horn",
    "to bomb",
    "to box someone in",
    "to bug someone",
    "to butt in",
    "to call it a day",
    "to chicken out",
    "to come out swinging",
    "to corner the market",
    "to cry wolf",
    "to draw a blank",
    "to drink like a fish",
    "to drop by",
    "to find fault with",
    "to follow up on something",
    "to get in touch with",
    "to get rid of",
    "to give in",
    "to go dutch",
    "to hold your own",
    "to keep an eye on",
    "to know by sight",
    "to live beyond your means",
    "to make matters worse",
    "to nix something",
    "to outdo oneself",
    "to paddle your own canoe",
    "to pony up",
    "to run",
    "to see the light",
    "to serve one right",
    "to smooth things over",
    "to stand up for",
    "to stonewall",
    "to take it easy",
    "to the hilt",
    "top dog",
    "touch and go",
    "touch base",
    "track record",
    "train of thought",
    "train wreck",
    "travel light",
    "troubled waters",
    "true blue",
    "tuckered out",
    "turn a blind eye",
    "turn a place upside down",
    "turn over a new leaf",
    "turn the other cheek",
    "turn the tables",
    "turn up the heat",
    "twist someone is arm",
    "two peas in a pod",
    "under a cloud",
    "under someone is thumb",
    "under the table",
    "under the weather",
    "under the wire",
    "until the cows come home",
    "up a blind alley",
    "up a gum tree",
    "up for grabs",
    "up in arms",
    "up in the air",
    "up to snuff",
    "upset the apple cart",
    "use your loaf",
    "veg out",
    "walk in someone is shoes",
    "walk in the park",
    "walking on air",
    "watch out for",
    "water under the bridge",
    "watering hole",
    "wave of the future",
    "we see eye to eye",
    "wear many different hats",
    "weasel out of something",
    "weather the storm",
    "well begun is half done",
    "went the extra mile",
    "wet behind the ears",
    "wet blanket",
    "wet my whistle",
    "when pigs fly",
    "when push comes to shove",
    "when the chips are down",
    "white elephant",
    "white lie",
    "whole ball of wax",
    "wild and woolly",
    "will take place",
    "wine and dine",
    "winging it",
    "with bated breath",
    "with bells on",
    "with flying colors",
    "wolf in sheep is clothing",
    "work against the clock",
    "worth one is salt",
    "would not be caught dead",
    "would not hurt a fly",
    "x marks the spot",
    "you are telling me",
    "you bet",
    "you can bet your boots",
    "you can say that again",
    "you have sold me",
    "zero tolerance",
    "zip it"
];
export { phrases };
